/**
 * Domaines CRCN (Cadre de Référence des Compétences Numériques)
 * Version complète avec tous les domaines et mots-clés associés pour la détection automatique
 */

export const crcnDomains = {
    // DOMAINE 1 : INFORMATION ET DONNÉES
    1.1: {
        name: "Mener une recherche et une veille d'information",
        keywords: [
            "recherche",
            "veille",
            "information",
            "moteur de recherche",
            "mots-clés",
            "recherche documentaire",
            "flux RSS",
            "curation",
            "agrégateur",
            "bookmarking",
            "source",
            "fiabilité",
            "pertinence",
            "alerte",
            "requête",
            "navigation",
            "critères de recherche",
            "mot-clé",
            "opérateur booléen",
            "filtre",
            "tri",
            "évaluation",
            "crédibilité",
            "référencement",
            "indexation",
            "collecte",
        ],
        description:
            "Effectuer une recherche d'information et mettre en place une veille informationnelle pour exploiter des résultats pertinents",
    },

    1.2: {
        name: "Gérer des données",
        keywords: [
            "stockage",
            "données",
            "sauvegarde",
            "classement",
            "organisation",
            "arborescence",
            "nommage",
            "métadonnées",
            "archivage",
            "synchronisation",
            "cloud",
            "import",
            "export",
            "base de données",
            "serveur",
            "hébergement",
            "structuration",
            "classification",
            "hiérarchisation",
            "format",
            "versioning",
            "dossier",
            "fichier",
            "compression",
            "duplication",
            "migration",
            "partage",
            "espace de stockage",
            "disque dur",
            "clé USB",
            "corbeille",
            "restauration",
        ],
        description:
            "Stocker, organiser et partager des documents et des données dans différents espaces numériques",
    },

    1.3: {
        name: "Traiter des données",
        keywords: [
            "données",
            "tableur",
            "formule",
            "calcul",
            "statistiques",
            "traitement",
            "tri",
            "filtre",
            "analyse",
            "visualisation",
            "graphique",
            "diagramme",
            "infographie",
            "open data",
            "big data",
            "data mining",
            "extraction",
            "pivot",
            "rapport",
            "modélisation",
            "simulation",
            "conversion",
            "agrégation",
            "datavisualisation",
            "moyenne",
            "somme",
            "tableau croisé",
            "matrice",
            "classement",
            "courbe",
            "histogramme",
            "camembert",
            "API",
            "XML",
            "JSON",
        ],
        description:
            "Exploiter des données structurées et automatiser leur traitement et leur analyse",
    },

    // DOMAINE 2 : COMMUNICATION ET COLLABORATION
    2.1: {
        name: "Interagir",
        keywords: [
            "messagerie",
            "email",
            "courriel",
            "forum",
            "chat",
            "visioconférence",
            "réseau social",
            "communication",
            "partage",
            "collaboration",
            "netiquette",
            "identité numérique",
            "profil",
            "liste de diffusion",
            "message",
            "pièce jointe",
            "conversation",
            "discussion",
            "commentaire",
            "modération",
            "réponse",
            "fil",
            "transfert",
            "copie cachée",
            "accusé de réception",
            "spam",
            "pourriel",
            "contact",
            "groupe",
            "carnet d'adresses",
            "destinataire",
            "expéditeur",
        ],
        description:
            "Communiquer avec les autres utilisateurs en ligne en adaptant ses pratiques selon les outils utilisés",
    },

    2.2: {
        name: "Partager et publier",
        keywords: [
            "publication",
            "partage",
            "diffusion",
            "blog",
            "site web",
            "réseau social",
            "public",
            "privé",
            "confidentialité",
            "droits",
            "licence",
            "copyright",
            "visibilité",
            "référencement",
            "audience",
            "lecteur",
            "abonné",
            "follower",
            "hashtag",
            "mot-dièse",
            "article",
            "billet",
            "post",
            "tweet",
            "story",
            "live",
            "streaming",
            "podcast",
            "chaîne",
            "vlog",
            "portfolio",
            "plateforme",
            "hébergement",
            "commentaire",
            "modération",
            "curation",
            "rediffusion",
            "repost",
            "viral",
        ],
        description:
            "Publier et partager en ligne en respectant les règles de propriété intellectuelle et de partage des données",
    },

    2.3: {
        name: "Collaborer",
        keywords: [
            "collaboration",
            "travail collaboratif",
            "outil collaboratif",
            "espace partagé",
            "document partagé",
            "wiki",
            "pad",
            "édition collaborative",
            "gestion de projet",
            "agenda partagé",
            "cloud",
            "coédition",
            "versionning",
            "git",
            "contribution",
            "modification",
            "historique",
            "révision",
            "conflit",
            "fusion",
            "brainstorming",
            "mind mapping",
            "carte mentale",
            "kanban",
            "tableau de bord",
            "tâche",
            "délai",
            "suivi",
            "notification",
            "commentaire",
            "suggestion",
            "validation",
            "workflow",
        ],
        description:
            "Travailler à plusieurs sur un même document ou projet au sein d'un espace de travail partagé",
    },

    2.4: {
        name: "S'insérer dans le monde numérique",
        keywords: [
            "identité numérique",
            "présence en ligne",
            "e-réputation",
            "trace numérique",
            "profil",
            "avatar",
            "citoyenneté numérique",
            "inclusion",
            "accessibilité",
            "fracture numérique",
            "médiation",
            "empreinte numérique",
            "données personnelles",
            "vie privée",
            "confidentialité",
            "paramètres",
            "cookies",
            "historique",
            "navigation",
            "authentification",
            "autorisation",
            "désinformation",
            "fake news",
            "hoax",
            "fact-checking",
            "vérification",
            "civisme",
            "éthique",
            "charte",
        ],
        description:
            "Maîtriser son identité numérique et respecter les règles de civilité tout en agissant de façon éthique",
    },

    // DOMAINE 3 : CRÉATION DE CONTENU
    3.1: {
        name: "Développer des documents textuels",
        keywords: [
            "traitement de texte",
            "mise en page",
            "style",
            "formatage",
            "document",
            "texte",
            "typographie",
            "police",
            "paragraphe",
            "tableau",
            "sommaire",
            "index",
            "export",
            "conversion",
            "PDF",
            "titre",
            "section",
            "chapitre",
            "en-tête",
            "pied de page",
            "numérotation",
            "note",
            "commentaire",
            "révision",
            "correction",
            "orthographe",
            "grammaire",
            "synonyme",
            "dictionnaire",
            "thésaurus",
            "colonne",
            "marge",
            "interligne",
            "espacement",
            "tabulation",
        ],
        description:
            "Créer, mettre en forme et modifier des documents textuels avec différents niveaux de complexité",
    },

    3.2: {
        name: "Développer des documents multimédia",
        keywords: [
            "image",
            "photo",
            "vidéo",
            "son",
            "audio",
            "multimédia",
            "montage",
            "retouche",
            "édition",
            "diaporama",
            "présentation",
            "animation",
            "format",
            "compression",
            "résolution",
            "codec",
            "appareil photo",
            "caméra",
            "microphone",
            "enregistrement",
            "capture",
            "numérisation",
            "scanner",
            "effet",
            "transition",
            "recadrage",
            "filtrage",
            "correction",
            "amélioration",
            "sous-titre",
            "doublage",
            "voix off",
            "mixage",
            "encodage",
            "streaming",
        ],
        description:
            "Créer, éditer et modifier différents types de médias (images, sons, vidéos) pour des productions multimédia",
    },

    3.3: {
        name: "Adapter les documents à leur finalité",
        keywords: [
            "publication",
            "diffusion",
            "format",
            "support",
            "adaptation",
            "conversion",
            "responsive",
            "accessibilité",
            "impression",
            "projection",
            "lecture",
            "ergonomie",
            "charte graphique",
            "identité visuelle",
            "template",
            "modèle",
            "gabarit",
            "export",
            "publication",
            "mise en ligne",
            "adaptation",
            "mobile",
            "tablette",
            "écran",
            "taille",
            "résolution",
            "orientation",
            "compatible",
            "interopérable",
            "portable",
            "multi-support",
            "multi-plateforme",
            "métadonnées",
        ],
        description:
            "Adapter un document à sa finalité en fonction du public cible et du contexte d'utilisation",
    },

    3.4: {
        name: "Programmer",
        keywords: [
            "algorithme",
            "programmation",
            "code",
            "script",
            "développement",
            "logiciel",
            "application",
            "langage",
            "scratch",
            "python",
            "html",
            "css",
            "javascript",
            "déboguer",
            "variable",
            "fonction",
            "boucle",
            "condition",
            "instruction",
            "séquence",
            "itération",
            "récursion",
            "événement",
            "objet",
            "classe",
            "méthode",
            "attribut",
            "héritage",
            "interface",
            "API",
            "framework",
            "bibliothèque",
            "package",
            "module",
            "compilation",
            "interprétation",
            "syntaxe",
        ],
        description:
            "Écrire des programmes et des algorithmes pour répondre à des problèmes ou automatiser des tâches",
    },

    // DOMAINE 4 : PROTECTION ET SÉCURITÉ
    4.1: {
        name: "Sécuriser l'environnement numérique",
        keywords: [
            "sécurité",
            "antivirus",
            "firewall",
            "pare-feu",
            "mise à jour",
            "correctif",
            "vulnérabilité",
            "authentification",
            "mot de passe",
            "chiffrement",
            "cryptage",
            "sauvegarde",
            "restauration",
            "virus",
            "malware",
            "ransomware",
            "phishing",
            "hameçonnage",
            "piratage",
            "intrusion",
            "backdoor",
            "porte dérobée",
            "trojan",
            "cheval de Troie",
            "keylogger",
            "spyware",
            "logiciel espion",
            "adware",
            "rootkit",
            "botnet",
            "DDoS",
            "attaque",
            "menace",
            "risque",
            "prévention",
            "détection",
            "correction",
            "isolation",
            "quarantaine",
            "désinfection",
        ],
        description:
            "Sécuriser les équipements, les communications et les données pour se prémunir contre les attaques",
    },

    4.2: {
        name: "Protéger les données personnelles et la vie privée",
        keywords: [
            "RGPD",
            "données personnelles",
            "vie privée",
            "confidentialité",
            "consentement",
            "cookies",
            "traceurs",
            "profilage",
            "anonymisation",
            "pseudonymisation",
            "droit à l'oubli",
            "portabilité",
            "CGU",
            "conditions d'utilisation",
            "politique",
            "confidentialité",
            "traçage",
            "géolocalisation",
            "biométrie",
            "identification",
            "authentification",
            "autorisation",
            "accès",
            "permission",
            "rôle",
            "habilitation",
            "contrôle",
            "audit",
            "journalisation",
            "log",
            "réclamation",
            "violation",
            "fuite",
        ],
        description:
            "Maîtriser ses données personnelles et protéger sa vie privée et celle des autres dans l'environnement numérique",
    },

    4.3: {
        name: "Protéger la santé, le bien-être et l'environnement",
        keywords: [
            "ergonomie",
            "posture",
            "fatigue visuelle",
            "addiction",
            "écrans",
            "ondes",
            "cyberharcèlement",
            "déconnexion",
            "énergie",
            "consommation",
            "recyclage",
            "numérique responsable",
            "impact environnemental",
            "empreinte carbone",
            "green IT",
            "éco-conception",
            "obsolescence",
            "durabilité",
            "réparabilité",
            "réutilisation",
            "reconditionnement",
            "TMS",
            "trouble musculo-squelettique",
            "sédentarité",
            "surexposition",
            "hyperconnexion",
            "nomophobie",
            "FOMO",
            "cyberdépendance",
            "e-déchets",
            "datacentre",
            "pollution numérique",
        ],
        description:
            "Adopter des comportements responsables pour préserver sa santé et l'environnement dans l'usage du numérique",
    },

    // DOMAINE 5 : ENVIRONNEMENT NUMÉRIQUE
    5.1: {
        name: "Résoudre des problèmes techniques",
        keywords: [
            "dépannage",
            "diagnostic",
            "incident",
            "erreur",
            "résolution",
            "assistance",
            "maintenance",
            "périphérique",
            "matériel",
            "logiciel",
            "pilote",
            "driver",
            "mise à jour",
            "compatibilité",
            "configuration",
            "panne",
            "bug",
            "plantage",
            "crash",
            "freeze",
            "gel",
            "redémarrage",
            "réinitialisation",
            "restauration",
            "récupération",
            "réparation",
            "optimisation",
            "performance",
            "ralentissement",
            "saturation",
            "espace disque",
            "mémoire",
            "processeur",
            "connexion",
            "réseau",
            "débit",
            "latence",
            "ping",
            "DNS",
            "IP",
            "port",
            "proxy",
            "VPN",
            "terminal",
        ],
        description:
            "Identifier et résoudre des problèmes techniques dans l'utilisation des outils numériques",
    },

    5.2: {
        name: "Construire un environnement numérique",
        keywords: [
            "système d'exploitation",
            "OS",
            "Windows",
            "macOS",
            "Linux",
            "Android",
            "iOS",
            "interface",
            "navigation",
            "personnalisation",
            "préférences",
            "profil",
            "compte",
            "utilisateur",
            "installation",
            "désinstallation",
            "paramètres",
            "mise à jour",
            "migration",
            "interopérabilité",
            "écosystème",
            "environnement",
            "bureau",
            "icône",
            "menu",
            "barre",
            "dock",
            "widget",
            "gadget",
            "extension",
            "plugin",
            "add-on",
            "thème",
            "apparence",
            "langue",
            "région",
            "clavier",
            "souris",
            "écran",
            "moniteur",
            "périphérique",
            "imprimante",
            "scanner",
            "appareil",
            "connectivité",
            "bluetooth",
        ],
        description:
            "Construire et organiser son environnement numérique personnel pour l'adapter à ses besoins",
    },

    5.3: {
        name: "Évoluer dans un environnement numérique",
        keywords: [
            "adaptation",
            "veille technologique",
            "innovation",
            "nouveauté",
            "évolution",
            "transition",
            "formation",
            "autoformation",
            "tutoriel",
            "aide",
            "manuel",
            "documentation",
            "communauté",
            "forum",
            "entraide",
            "support",
            "assistance",
            "mise à niveau",
            "compétences",
            "maîtrise",
            "appropriation",
            "autonomie",
            "découverte",
            "exploration",
            "expérimentation",
            "test",
            "essai",
            "évaluation",
            "comparaison",
            "alternative",
            "solution",
            "outil",
            "service",
            "plateforme",
            "intégration",
            "apprentissage",
            "développement",
            "progression",
            "certification",
        ],
        description:
            "Suivre l'évolution des outils numériques et développer son autonomie dans leur utilisation",
    },
};

export default crcnDomains;
