/**
 * Liste des mots-clés RGPD sensibles à détecter dans les documents
 */

export const rgpdKeywords = [
    // Données personnelles
    "nom complet",
    "prénom",
    "nom de famille",
    "date de naissance",
    "lieu de naissance",
    "adresse personnelle",
    "adresse domicile",
    "numéro de téléphone",
    "téléphone portable",
    "téléphone fixe",
    "email personnel",
    "courriel personnel",
    "adresse mail personnelle",
    "photo d'identité",
    "photographie d'élève",
    "trombinoscope",

    // Identifiants et données administratives
    "numéro de sécurité sociale",
    "NIR",
    "INSEE",
    "INE",
    "identifiant national élève",
    "numéro fiscal",
    "identifiant fiscal",
    "identifiant académique",
    "UAI",
    "RNE",
    "code établissement",
    "NUMEN",
    "identifiant enseignant",

    // Données sensibles
    "handicap",
    "situation de handicap",
    "MDPH",
    "notification MDPH",
    "santé",
    "allergie",
    "PAI",
    "protocole médical",
    "origine ethnique",
    "opinion politique",
    "conviction religieuse",
    "orientation sexuelle",
    "vie sexuelle",
    "situation familiale",
    "famille monoparentale",
    "famille d'accueil",
    "mesure éducative",
    "AEMO",
    "suivi éducatif",
    "ASE",

    // Données comportementales et évaluatives
    "comportement",
    "attitude",
    "sanction",
    "punition",
    "incident",
    "violence",
    "absentéisme",
    "retard",
    "notes",
    "évaluation individuelle",
    "résultats scolaires",
    "livret scolaire",
    "livret personnel de compétences",
    "bulletin",

    // Mineurs et consentement
    "élève mineur",
    "enfant",
    "consentement parental",
    "autorisation parentale",
    "responsable légal",
    "droit à l'image",
    "autorisation de filmer",
    "autorisation de photographier",

    // Termes généraux RGPD
    "donnée personnelle",
    "données personnelles",
    "traitement de données",
    "finalité",
    "base légale",
    "consentement",
    "formulaire de consentement",
    "droit d'accès",
    "droit de rectification",
    "droit d'opposition",
    "droit à l'oubli",
    "violation de données",
    "fuite de données",
    "incident de sécurité",
    "confidentialité",
    "anonymisation",
    "pseudonymisation",
];

export default rgpdKeywords;
